// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameWBot = "w_bot"

// WBot mapped from table <w_bot>
type WBot struct {
	ID        int32  `gorm:"column:id ;type:INTEGER" json:"id "`
	BotName   string `gorm:"column:bot_name;not null" json:"bot_name"`
	BotToken  string `gorm:"column:bot_token;not null" json:"bot_token"`
	CreatedAt string `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt string `gorm:"column:updated_at;not null" json:"updated_at"`
}

// TableName WBot's table name
func (*WBot) TableName() string {
	return TableNameWBot
}
